org: myorgluis

service: reservas

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'local'}

plugins:
  - serverless-offline

functions:
  ping:
    handler: src/interfaces/http/ping.handler
    events:
      - httpApi:
          path: /ping
          method: get
  getBooking:
    handler: src/interfaces/http/get-booking.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: get

  postBookings:
    handler: src/interfaces/http/post-bookings.handler
    events:
      - httpApi:
          path: /bookings
          method: post